apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argo-cd
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: 3.2.4
    helm:
      releaseName: kyverno
      values: |
        webhooksCleanup:
          securityContext:
            runAsUser: null
            runAsGroup: null
        policyReportsCleanup:
          securityContext:
            runAsUser: null
            runAsGroup: null
        config:
          webhooks:
            - namespaceSelector:
                matchExpressions:
                  - key: kubernetes.io/metadata.name
                    operator: NotIn
                    values:
                      - kube-system
                      - kyverno
                      - argo-cd
                      - openshift
                      - openshift-apiserver
                      - openshift-apiserver-operator
                      - openshift-authentication
                      - openshift-authentication-operator
                      - openshift-cloud-controller-manager
                      - openshift-cloud-controller-manager-operator
                      - openshift-cloud-credential-operator
                      - openshift-cloud-network-config-controller
                      - openshift-cluster-csi-drivers
                      - openshift-cluster-machine-approver
                      - openshift-cluster-node-tuning-operator
                      - openshift-cluster-samples-operator
                      - openshift-cluster-storage-operator
                      - openshift-cluster-version
                      - openshift-config
                      - openshift-config-managed
                      - openshift-config-operator
                      - openshift-console
                      - openshift-console-operator
                      - openshift-console-user-settings
                      - openshift-controller-manager
                      - openshift-controller-manager-operator
                      - openshift-debug-node-8rkbw
                      - openshift-debug-node-hvg44
                      - openshift-debug-node-pd55b
                      - openshift-dns
                      - openshift-dns-operator
                      - openshift-etcd
                      - openshift-etcd-operator
                      - openshift-gitops
                      - openshift-host-network
                      - openshift-image-registry
                      - openshift-infra
                      - openshift-ingress
                      - openshift-ingress-canary
                      - openshift-ingress-operator
                      - openshift-insights
                      - openshift-kni-infra
                      - openshift-kube-apiserver
                      - openshift-kube-apiserver-operator
                      - openshift-kube-controller-manager
                      - openshift-kube-controller-manager-operator
                      - openshift-kube-scheduler
                      - openshift-kube-scheduler-operator
                      - openshift-kube-storage-version-migrator
                      - openshift-kube-storage-version-migrator-operator
                      - openshift-logging
                      - openshift-machine-api
                      - openshift-machine-config-operator
                      - openshift-marketplace
                      - openshift-monitoring
                      - openshift-multus
                      - openshift-network-diagnostics
                      - openshift-network-operator
                      - openshift-node
                      - openshift-nutanix-infra
                      - openshift-oauth-apiserver
                      - openshift-openstack-infra
                      - openshift-operator-lifecycle-manager
                      - openshift-operators
                      - openshift-operators-redhat
                      - openshift-ovirt-infra
                      - openshift-ovn-kubernetes
                      - openshift-route-controller-manager
                      - openshift-service-ca
                      - openshift-service-ca-operator
                      - openshift-user-workload-monitoring
                      - openshift-vertical-pod-autoscaler
                      - openshift-vsphere-infra
        admissionController:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: env
                      operator: In
                      values:
                        - infra
                weight: 1
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - admission-controller
                  topologyKey: kubernetes.io/hostname
                weight: 1
          replicas: 3
          serviceMonitor:
            enabled: false
          tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
        backgroundController:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: env
                      operator: In
                      values:
                        - infra
                weight: 1
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - background-controller
                  topologyKey: kubernetes.io/hostname
                weight: 1
          replicas: 2
          resources: {}
          serviceMonitor:
            enabled: false
          tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
        cleanupController:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: env
                      operator: In
                      values:
                        - infra
                weight: 1
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - cleanup-controller
                  topologyKey: kubernetes.io/hostname
                weight: 1
          replicas: 2
          resources: {}
          serviceMonitor:
            enabled: false
          tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
        reportsController:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - preference:
                  matchExpressions:
                    - key: env
                      operator: In
                      values:
                        - infra
                weight: 1
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/component
                        operator: In
                        values:
                          - reports-controller
                  topologyKey: kubernetes.io/hostname
                weight: 1
          replicas: 2
          resources: {}
          serviceMonitor:
            enabled: false
          tolerations:
            - key: infra
              value: reserved
              effect: NoSchedule
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
