apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: ocp-hml
  namespace: argo-cd
spec:
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/ocp-hml
    repoURL: https://github.com/mmmarceleza/openshift-iac
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
